/******************************************************************************
**
** <auto-generated>
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.6.12, using .NET Server 4.0.0 template (version 0)
**
**     Changes to this file may cause incorrect behavior and will be lost if
**     the code is regenerated.
** </auto-generated>
**
** Copyright (c) 2006-2024 Unified Automation GmbH All rights reserved.
**
** Software License Agreement ("SLA") Version 2.8
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.8, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** Project: .NET OPC UA SDK information model for namespace http://yourorganisation.org/ModeloEvaporador/
**
** Description: OPC Unified Architecture Software Development Kit.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.8/
**
** Created: 22.06.2024
**
******************************************************************************/

using System;
using System.Collections.Generic;
using System.Text;
using System.Reflection;
using System.Xml;
using System.Runtime.Serialization;
using UnifiedAutomation.UaBase;

namespace UFCG.ModeloEvaporadorNS
{
    #region DataType Identifiers
    /// <summary>
    /// A class that declares constants for all DataTypes in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.12")]
    public static partial class DataTypes
    {
    }
    #endregion

    #region Object Identifiers
    /// <summary>
    /// A class that declares constants for all Objects in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.12")]
    public static partial class Objects
    {
        /// <summary>
        /// The identifier for the T1paraT2 Object.
        /// </summary>
        public const uint PlantaEvaporador_T1paraT2 = 5002;

        /// <summary>
        /// The identifier for the T1paraT3 Object.
        /// </summary>
        public const uint PlantaEvaporador_T1paraT3 = 5003;

        /// <summary>
        /// The identifier for the T2paraCX Object.
        /// </summary>
        public const uint PlantaEvaporador_T2paraCX = 5004;

        /// <summary>
        /// The identifier for the T3paraCX Object.
        /// </summary>
        public const uint PlantaEvaporador_T3paraCX = 5005;

        /// <summary>
        /// The identifier for the Tanque001 Object.
        /// </summary>
        public const uint PlantaEvaporador_Tanque001 = 5006;

        /// <summary>
        /// The identifier for the Tanque002 Object.
        /// </summary>
        public const uint PlantaEvaporador_Tanque002 = 5007;

        /// <summary>
        /// The identifier for the Tanque003 Object.
        /// </summary>
        public const uint PlantaEvaporador_Tanque003 = 5008;

        /// <summary>
        /// The identifier for the http://yourorganisation.org/ModeloEvaporador/ Object.
        /// </summary>
        public const uint Namespaces_http___yourorganisation_org_ModeloEvaporador_ = 5001;

    }
    #endregion

    #region ObjectType Identifiers
    /// <summary>
    /// A class that declares constants for all ObjectTypes in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.12")]
    public static partial class ObjectTypes
    {
        /// <summary>
        /// The identifier for the PlantaEvaporador ObjectType.
        /// </summary>
        public const uint PlantaEvaporador = 1009;

        /// <summary>
        /// The identifier for the T1paraT2 ObjectType.
        /// </summary>
        public const uint T1paraT2 = 1003;

        /// <summary>
        /// The identifier for the T1paraT3 ObjectType.
        /// </summary>
        public const uint T1paraT3 = 1004;

        /// <summary>
        /// The identifier for the T2paraCX ObjectType.
        /// </summary>
        public const uint T2paraCX = 1007;

        /// <summary>
        /// The identifier for the T3paraCX ObjectType.
        /// </summary>
        public const uint T3paraCX = 1010;

        /// <summary>
        /// The identifier for the Tanque001 ObjectType.
        /// </summary>
        public const uint Tanque001 = 1013;

        /// <summary>
        /// The identifier for the Tanque002 ObjectType.
        /// </summary>
        public const uint Tanque002 = 1016;

        /// <summary>
        /// The identifier for the Tanque003 ObjectType.
        /// </summary>
        public const uint Tanque003 = 1005;

    }
    #endregion

    #region Method Identifiers
    /// <summary>
    /// A class that declares constants for all Methods in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.12")]
    public static partial class Methods
    {
    }
    #endregion

    #region ReferenceType Identifiers
    /// <summary>
    /// A class that declares constants for all ReferenceTyped in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.12")]
    public static partial class ReferenceTypes
    {
    }
    #endregion

    #region Variable Identifiers
    /// <summary>
    /// A class that declares constants for all Variables in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.12")]
    public static partial class Variables
    {
        /// <summary>
        /// The identifier for the SC-001 Variable.
        /// </summary>
        public const uint PlantaEvaporador_T1paraT2_SC_001 = 6022;

        /// <summary>
        /// The identifier for the SC-003 Variable.
        /// </summary>
        public const uint PlantaEvaporador_T1paraT3_SC_003 = 6023;

        /// <summary>
        /// The identifier for the FV-002 Variable.
        /// </summary>
        public const uint PlantaEvaporador_T2paraCX_FV_002 = 6024;

        /// <summary>
        /// The identifier for the FV-001 Variable.
        /// </summary>
        public const uint PlantaEvaporador_T3paraCX_FV_001 = 6025;

        /// <summary>
        /// The identifier for the SC-002 Variable.
        /// </summary>
        public const uint PlantaEvaporador_T3paraCX_SC_002 = 6026;

        /// <summary>
        /// The identifier for the TT-002 Variable.
        /// </summary>
        public const uint PlantaEvaporador_T3paraCX_TT_002 = 6027;

        /// <summary>
        /// The identifier for the TT-003 Variable.
        /// </summary>
        public const uint PlantaEvaporador_Tanque001_TT_003 = 6028;

        /// <summary>
        /// The identifier for the TT-001 Variable.
        /// </summary>
        public const uint PlantaEvaporador_Tanque002_TT_001 = 6029;

        /// <summary>
        /// The identifier for the TV-001 Variable.
        /// </summary>
        public const uint PlantaEvaporador_Tanque002_TV_001 = 6030;

        /// <summary>
        /// The identifier for the LT-001 Variable.
        /// </summary>
        public const uint PlantaEvaporador_Tanque003_LT_001 = 6031;

        /// <summary>
        /// The identifier for the PT-001 Variable.
        /// </summary>
        public const uint PlantaEvaporador_Tanque003_PT_001 = 6032;

        /// <summary>
        /// The identifier for the SC-001 Variable.
        /// </summary>
        public const uint T1paraT2_SC_001 = 6011;

        /// <summary>
        /// The identifier for the SC-003 Variable.
        /// </summary>
        public const uint T1paraT3_SC_003 = 6012;

        /// <summary>
        /// The identifier for the FV-002 Variable.
        /// </summary>
        public const uint T2paraCX_FV_002 = 6013;

        /// <summary>
        /// The identifier for the FV-001 Variable.
        /// </summary>
        public const uint T3paraCX_FV_001 = 6014;

        /// <summary>
        /// The identifier for the SC-002 Variable.
        /// </summary>
        public const uint T3paraCX_SC_002 = 6015;

        /// <summary>
        /// The identifier for the TT-002 Variable.
        /// </summary>
        public const uint T3paraCX_TT_002 = 6016;

        /// <summary>
        /// The identifier for the TT-003 Variable.
        /// </summary>
        public const uint Tanque001_TT_003 = 6017;

        /// <summary>
        /// The identifier for the TT-001 Variable.
        /// </summary>
        public const uint Tanque002_TT_001 = 6018;

        /// <summary>
        /// The identifier for the TV-001 Variable.
        /// </summary>
        public const uint Tanque002_TV_001 = 6019;

        /// <summary>
        /// The identifier for the LT-001 Variable.
        /// </summary>
        public const uint Tanque003_LT_001 = 6020;

        /// <summary>
        /// The identifier for the PT-001 Variable.
        /// </summary>
        public const uint Tanque003_PT_001 = 6021;

        /// <summary>
        /// The identifier for the DefaultAccessRestrictions Object.
        /// </summary>
        public const uint Namespaces_http___yourorganisation_org_ModeloEvaporador__DefaultAccessRestrictions = 6010;

        /// <summary>
        /// The identifier for the DefaultRolePermissions Object.
        /// </summary>
        public const uint Namespaces_http___yourorganisation_org_ModeloEvaporador__DefaultRolePermissions = 6008;

        /// <summary>
        /// The identifier for the DefaultUserRolePermissions Object.
        /// </summary>
        public const uint Namespaces_http___yourorganisation_org_ModeloEvaporador__DefaultUserRolePermissions = 6009;

        /// <summary>
        /// The identifier for the IsNamespaceSubset Object.
        /// </summary>
        public const uint Namespaces_http___yourorganisation_org_ModeloEvaporador__IsNamespaceSubset = 6001;

        /// <summary>
        /// The identifier for the NamespacePublicationDate Object.
        /// </summary>
        public const uint Namespaces_http___yourorganisation_org_ModeloEvaporador__NamespacePublicationDate = 6002;

        /// <summary>
        /// The identifier for the NamespaceUri Object.
        /// </summary>
        public const uint Namespaces_http___yourorganisation_org_ModeloEvaporador__NamespaceUri = 6003;

        /// <summary>
        /// The identifier for the NamespaceVersion Object.
        /// </summary>
        public const uint Namespaces_http___yourorganisation_org_ModeloEvaporador__NamespaceVersion = 6004;

        /// <summary>
        /// The identifier for the StaticNodeIdTypes Object.
        /// </summary>
        public const uint Namespaces_http___yourorganisation_org_ModeloEvaporador__StaticNodeIdTypes = 6005;

        /// <summary>
        /// The identifier for the StaticNumericNodeIdRange Object.
        /// </summary>
        public const uint Namespaces_http___yourorganisation_org_ModeloEvaporador__StaticNumericNodeIdRange = 6006;

        /// <summary>
        /// The identifier for the StaticStringNodeIdPattern Object.
        /// </summary>
        public const uint Namespaces_http___yourorganisation_org_ModeloEvaporador__StaticStringNodeIdPattern = 6007;

    }
    #endregion

    #region VariableTypes Identifiers
    /// <summary>
    /// A class that declares constants for all VariableTypes in the Model.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.12")]
    public static partial class VariableTypes
    {
    }
    #endregion

    #region DataType Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all DataTypes in the Model.
    /// </summary>
    /// <remarks>
    /// Call ExpandedNodeId.ToNodeId to use these constants.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.12")]
    public static partial class DataTypeIds
    {
    }
    #endregion

    #region Method Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all Methods in the Model.
    /// </summary>
    /// <remarks>
    /// Call ExpandedNodeId.ToNodeId to use these constants.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.12")]
    public static partial class MethodIds
    {
    }
    #endregion

    #region Object Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all Objects in the Model.
    /// </summary>
    /// <remarks>
    /// Call ExpandedNodeId.ToNodeId to use these constants.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.12")]
    public static partial class ObjectIds
    {
        /// <summary>
        /// The identifier for the PlantaEvaporador_T1paraT2 Object.
        /// </summary>
        public static readonly ExpandedNodeId PlantaEvaporador_T1paraT2 = new ExpandedNodeId(Objects.PlantaEvaporador_T1paraT2, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the PlantaEvaporador_T1paraT3 Object.
        /// </summary>
        public static readonly ExpandedNodeId PlantaEvaporador_T1paraT3 = new ExpandedNodeId(Objects.PlantaEvaporador_T1paraT3, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the PlantaEvaporador_T2paraCX Object.
        /// </summary>
        public static readonly ExpandedNodeId PlantaEvaporador_T2paraCX = new ExpandedNodeId(Objects.PlantaEvaporador_T2paraCX, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the PlantaEvaporador_T3paraCX Object.
        /// </summary>
        public static readonly ExpandedNodeId PlantaEvaporador_T3paraCX = new ExpandedNodeId(Objects.PlantaEvaporador_T3paraCX, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the PlantaEvaporador_Tanque001 Object.
        /// </summary>
        public static readonly ExpandedNodeId PlantaEvaporador_Tanque001 = new ExpandedNodeId(Objects.PlantaEvaporador_Tanque001, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the PlantaEvaporador_Tanque002 Object.
        /// </summary>
        public static readonly ExpandedNodeId PlantaEvaporador_Tanque002 = new ExpandedNodeId(Objects.PlantaEvaporador_Tanque002, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the PlantaEvaporador_Tanque003 Object.
        /// </summary>
        public static readonly ExpandedNodeId PlantaEvaporador_Tanque003 = new ExpandedNodeId(Objects.PlantaEvaporador_Tanque003, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the Namespaces_http___yourorganisation_org_ModeloEvaporador_ Object.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___yourorganisation_org_ModeloEvaporador_ = new ExpandedNodeId(Objects.Namespaces_http___yourorganisation_org_ModeloEvaporador_, Namespaces.ModeloEvaporadorNS);

    }
    #endregion

    #region ObjectType Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all Objects in the Model.
    /// </summary>
    /// <remarks>
    /// Call ExpandedNodeId.ToNodeId to use these constants.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.12")]
    public static partial class ObjectTypeIds
    {
        /// <summary>
        /// The identifier for the PlantaEvaporador ObjectType.
        /// </summary>
        public static readonly ExpandedNodeId PlantaEvaporador = new ExpandedNodeId(ObjectTypes.PlantaEvaporador, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the T1paraT2 ObjectType.
        /// </summary>
        public static readonly ExpandedNodeId T1paraT2 = new ExpandedNodeId(ObjectTypes.T1paraT2, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the T1paraT3 ObjectType.
        /// </summary>
        public static readonly ExpandedNodeId T1paraT3 = new ExpandedNodeId(ObjectTypes.T1paraT3, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the T2paraCX ObjectType.
        /// </summary>
        public static readonly ExpandedNodeId T2paraCX = new ExpandedNodeId(ObjectTypes.T2paraCX, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the T3paraCX ObjectType.
        /// </summary>
        public static readonly ExpandedNodeId T3paraCX = new ExpandedNodeId(ObjectTypes.T3paraCX, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the Tanque001 ObjectType.
        /// </summary>
        public static readonly ExpandedNodeId Tanque001 = new ExpandedNodeId(ObjectTypes.Tanque001, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the Tanque002 ObjectType.
        /// </summary>
        public static readonly ExpandedNodeId Tanque002 = new ExpandedNodeId(ObjectTypes.Tanque002, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the Tanque003 ObjectType.
        /// </summary>
        public static readonly ExpandedNodeId Tanque003 = new ExpandedNodeId(ObjectTypes.Tanque003, Namespaces.ModeloEvaporadorNS);

    }
    #endregion

    #region ReferenceType Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all ReferenceTypes in the Model.
    /// </summary>
    /// <remarks>
    /// Call ExpandedNodeId.ToNodeId to use these constants.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.12")]
    public static partial class ReferenceTypeIds
    {
    }
    #endregion

    #region Variable Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all Variables in the Model.
    /// </summary>
    /// <remarks>
    /// Call ExpandedNodeId.ToNodeId to use these constants.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.12")]
    public static partial class VariableIds
    {
        /// <summary>
        /// The identifier for the PlantaEvaporador_T1paraT2_SC_001 Variable.
        /// </summary>
        public static readonly ExpandedNodeId PlantaEvaporador_T1paraT2_SC_001 = new ExpandedNodeId(Variables.PlantaEvaporador_T1paraT2_SC_001, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the PlantaEvaporador_T1paraT3_SC_003 Variable.
        /// </summary>
        public static readonly ExpandedNodeId PlantaEvaporador_T1paraT3_SC_003 = new ExpandedNodeId(Variables.PlantaEvaporador_T1paraT3_SC_003, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the PlantaEvaporador_T2paraCX_FV_002 Variable.
        /// </summary>
        public static readonly ExpandedNodeId PlantaEvaporador_T2paraCX_FV_002 = new ExpandedNodeId(Variables.PlantaEvaporador_T2paraCX_FV_002, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the PlantaEvaporador_T3paraCX_FV_001 Variable.
        /// </summary>
        public static readonly ExpandedNodeId PlantaEvaporador_T3paraCX_FV_001 = new ExpandedNodeId(Variables.PlantaEvaporador_T3paraCX_FV_001, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the PlantaEvaporador_T3paraCX_SC_002 Variable.
        /// </summary>
        public static readonly ExpandedNodeId PlantaEvaporador_T3paraCX_SC_002 = new ExpandedNodeId(Variables.PlantaEvaporador_T3paraCX_SC_002, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the PlantaEvaporador_T3paraCX_TT_002 Variable.
        /// </summary>
        public static readonly ExpandedNodeId PlantaEvaporador_T3paraCX_TT_002 = new ExpandedNodeId(Variables.PlantaEvaporador_T3paraCX_TT_002, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the PlantaEvaporador_Tanque001_TT_003 Variable.
        /// </summary>
        public static readonly ExpandedNodeId PlantaEvaporador_Tanque001_TT_003 = new ExpandedNodeId(Variables.PlantaEvaporador_Tanque001_TT_003, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the PlantaEvaporador_Tanque002_TT_001 Variable.
        /// </summary>
        public static readonly ExpandedNodeId PlantaEvaporador_Tanque002_TT_001 = new ExpandedNodeId(Variables.PlantaEvaporador_Tanque002_TT_001, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the PlantaEvaporador_Tanque002_TV_001 Variable.
        /// </summary>
        public static readonly ExpandedNodeId PlantaEvaporador_Tanque002_TV_001 = new ExpandedNodeId(Variables.PlantaEvaporador_Tanque002_TV_001, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the PlantaEvaporador_Tanque003_LT_001 Variable.
        /// </summary>
        public static readonly ExpandedNodeId PlantaEvaporador_Tanque003_LT_001 = new ExpandedNodeId(Variables.PlantaEvaporador_Tanque003_LT_001, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the PlantaEvaporador_Tanque003_PT_001 Variable.
        /// </summary>
        public static readonly ExpandedNodeId PlantaEvaporador_Tanque003_PT_001 = new ExpandedNodeId(Variables.PlantaEvaporador_Tanque003_PT_001, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the T1paraT2_SC_001 Variable.
        /// </summary>
        public static readonly ExpandedNodeId T1paraT2_SC_001 = new ExpandedNodeId(Variables.T1paraT2_SC_001, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the T1paraT3_SC_003 Variable.
        /// </summary>
        public static readonly ExpandedNodeId T1paraT3_SC_003 = new ExpandedNodeId(Variables.T1paraT3_SC_003, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the T2paraCX_FV_002 Variable.
        /// </summary>
        public static readonly ExpandedNodeId T2paraCX_FV_002 = new ExpandedNodeId(Variables.T2paraCX_FV_002, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the T3paraCX_FV_001 Variable.
        /// </summary>
        public static readonly ExpandedNodeId T3paraCX_FV_001 = new ExpandedNodeId(Variables.T3paraCX_FV_001, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the T3paraCX_SC_002 Variable.
        /// </summary>
        public static readonly ExpandedNodeId T3paraCX_SC_002 = new ExpandedNodeId(Variables.T3paraCX_SC_002, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the T3paraCX_TT_002 Variable.
        /// </summary>
        public static readonly ExpandedNodeId T3paraCX_TT_002 = new ExpandedNodeId(Variables.T3paraCX_TT_002, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the Tanque001_TT_003 Variable.
        /// </summary>
        public static readonly ExpandedNodeId Tanque001_TT_003 = new ExpandedNodeId(Variables.Tanque001_TT_003, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the Tanque002_TT_001 Variable.
        /// </summary>
        public static readonly ExpandedNodeId Tanque002_TT_001 = new ExpandedNodeId(Variables.Tanque002_TT_001, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the Tanque002_TV_001 Variable.
        /// </summary>
        public static readonly ExpandedNodeId Tanque002_TV_001 = new ExpandedNodeId(Variables.Tanque002_TV_001, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the Tanque003_LT_001 Variable.
        /// </summary>
        public static readonly ExpandedNodeId Tanque003_LT_001 = new ExpandedNodeId(Variables.Tanque003_LT_001, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the Tanque003_PT_001 Variable.
        /// </summary>
        public static readonly ExpandedNodeId Tanque003_PT_001 = new ExpandedNodeId(Variables.Tanque003_PT_001, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the Namespaces_http___yourorganisation_org_ModeloEvaporador__DefaultAccessRestrictions Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___yourorganisation_org_ModeloEvaporador__DefaultAccessRestrictions = new ExpandedNodeId(Variables.Namespaces_http___yourorganisation_org_ModeloEvaporador__DefaultAccessRestrictions, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the Namespaces_http___yourorganisation_org_ModeloEvaporador__DefaultRolePermissions Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___yourorganisation_org_ModeloEvaporador__DefaultRolePermissions = new ExpandedNodeId(Variables.Namespaces_http___yourorganisation_org_ModeloEvaporador__DefaultRolePermissions, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the Namespaces_http___yourorganisation_org_ModeloEvaporador__DefaultUserRolePermissions Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___yourorganisation_org_ModeloEvaporador__DefaultUserRolePermissions = new ExpandedNodeId(Variables.Namespaces_http___yourorganisation_org_ModeloEvaporador__DefaultUserRolePermissions, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the Namespaces_http___yourorganisation_org_ModeloEvaporador__IsNamespaceSubset Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___yourorganisation_org_ModeloEvaporador__IsNamespaceSubset = new ExpandedNodeId(Variables.Namespaces_http___yourorganisation_org_ModeloEvaporador__IsNamespaceSubset, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the Namespaces_http___yourorganisation_org_ModeloEvaporador__NamespacePublicationDate Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___yourorganisation_org_ModeloEvaporador__NamespacePublicationDate = new ExpandedNodeId(Variables.Namespaces_http___yourorganisation_org_ModeloEvaporador__NamespacePublicationDate, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the Namespaces_http___yourorganisation_org_ModeloEvaporador__NamespaceUri Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___yourorganisation_org_ModeloEvaporador__NamespaceUri = new ExpandedNodeId(Variables.Namespaces_http___yourorganisation_org_ModeloEvaporador__NamespaceUri, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the Namespaces_http___yourorganisation_org_ModeloEvaporador__NamespaceVersion Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___yourorganisation_org_ModeloEvaporador__NamespaceVersion = new ExpandedNodeId(Variables.Namespaces_http___yourorganisation_org_ModeloEvaporador__NamespaceVersion, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the Namespaces_http___yourorganisation_org_ModeloEvaporador__StaticNodeIdTypes Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___yourorganisation_org_ModeloEvaporador__StaticNodeIdTypes = new ExpandedNodeId(Variables.Namespaces_http___yourorganisation_org_ModeloEvaporador__StaticNodeIdTypes, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the Namespaces_http___yourorganisation_org_ModeloEvaporador__StaticNumericNodeIdRange Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___yourorganisation_org_ModeloEvaporador__StaticNumericNodeIdRange = new ExpandedNodeId(Variables.Namespaces_http___yourorganisation_org_ModeloEvaporador__StaticNumericNodeIdRange, Namespaces.ModeloEvaporadorNS);

        /// <summary>
        /// The identifier for the Namespaces_http___yourorganisation_org_ModeloEvaporador__StaticStringNodeIdPattern Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___yourorganisation_org_ModeloEvaporador__StaticStringNodeIdPattern = new ExpandedNodeId(Variables.Namespaces_http___yourorganisation_org_ModeloEvaporador__StaticStringNodeIdPattern, Namespaces.ModeloEvaporadorNS);

    }
    #endregion

    #region VariableType Node Identifiers
    /// <summary>
    /// A class that declares ExpandedNodeIds for all VariableType in the Model.
    /// </summary>
    /// <remarks>
    /// Call ExpandedNodeId.ToNodeId to use these constants.
    /// </remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("UaModeler", "1.6.12")]
    public static partial class VariableTypeIds
    {
    }
    #endregion

    #region BrowseName Declarations
    /// <summary>
    /// Declares all of the BrowseNames used in the Model.
    /// </summary>
    public static partial class BrowseNames
    {
        /// <summary>
        /// The BrowseName for the FV-001 component.
        /// </summary>
        public const string FV_001 = "FV-001";
        /// <summary>
        /// The BrowseName for the FV-002 component.
        /// </summary>
        public const string FV_002 = "FV-002";
        /// <summary>
        /// The BrowseName for the LT-001 component.
        /// </summary>
        public const string LT_001 = "LT-001";
        /// <summary>
        /// The BrowseName for the PT-001 component.
        /// </summary>
        public const string PT_001 = "PT-001";
        /// <summary>
        /// The BrowseName for the PlantaEvaporador component.
        /// </summary>
        public const string PlantaEvaporador = "PlantaEvaporador";
        /// <summary>
        /// The BrowseName for the SC-001 component.
        /// </summary>
        public const string SC_001 = "SC-001";
        /// <summary>
        /// The BrowseName for the SC-002 component.
        /// </summary>
        public const string SC_002 = "SC-002";
        /// <summary>
        /// The BrowseName for the SC-003 component.
        /// </summary>
        public const string SC_003 = "SC-003";
        /// <summary>
        /// The BrowseName for the T1paraT2 component.
        /// </summary>
        public const string T1paraT2 = "T1paraT2";
        /// <summary>
        /// The BrowseName for the T1paraT3 component.
        /// </summary>
        public const string T1paraT3 = "T1paraT3";
        /// <summary>
        /// The BrowseName for the T2paraCX component.
        /// </summary>
        public const string T2paraCX = "T2paraCX";
        /// <summary>
        /// The BrowseName for the T3paraCX component.
        /// </summary>
        public const string T3paraCX = "T3paraCX";
        /// <summary>
        /// The BrowseName for the TT-001 component.
        /// </summary>
        public const string TT_001 = "TT-001";
        /// <summary>
        /// The BrowseName for the TT-002 component.
        /// </summary>
        public const string TT_002 = "TT-002";
        /// <summary>
        /// The BrowseName for the TT-003 component.
        /// </summary>
        public const string TT_003 = "TT-003";
        /// <summary>
        /// The BrowseName for the TV-001 component.
        /// </summary>
        public const string TV_001 = "TV-001";
        /// <summary>
        /// The BrowseName for the Tanque001 component.
        /// </summary>
        public const string Tanque001 = "Tanque001";
        /// <summary>
        /// The BrowseName for the Tanque002 component.
        /// </summary>
        public const string Tanque002 = "Tanque002";
        /// <summary>
        /// The BrowseName for the Tanque003 component.
        /// </summary>
        public const string Tanque003 = "Tanque003";
        /// <summary>
        /// The BrowseName for the http://yourorganisation.org/ModeloEvaporador/ component.
        /// </summary>
        public const string http___yourorganisation_org_ModeloEvaporador_ = "http://yourorganisation.org/ModeloEvaporador/";
    }
    #endregion

    #region Namespace Declarations
    /// <summary>
    /// Defines constants for all namespaces referenced by the Model.
    /// </summary>
    public static partial class Namespaces
    {
        /// <summary>
        /// The URI for the OpcUa namespace (.NET code namespace is 'Opc.Ua').
        /// </summary>
        public const string OpcUa = "http://opcfoundation.org/UA/";

        /// <summary>
        /// The URI for the OpcUaXsd namespace (.NET code namespace is 'Opc.Ua').
        /// </summary>
        public const string OpcUaXsd = "http://opcfoundation.org/UA/2008/02/Types.xsd";

        /// <summary>
        /// The URI for the ModeloEvaporadorNS namespace.
        /// </summary>
        public const string ModeloEvaporadorNS = "http://yourorganisation.org/ModeloEvaporador/";

        /// <summary>
        /// The URI for the ModeloEvaporadorNSXsd namespace.
        /// </summary>
        public const string ModeloEvaporadorNSXsd = "http://yourorganisation.org/ModeloEvaporador/Types.xsd";
    }
    #endregion
}

